### ISSUE TITLE
Idiomatic way to apply a monadic action to the stream

### ISSUE THREAD

**Issue by PierreR** [nilcons/nc-indicators#2]
Hi,

I have been discussing `execU` on the Pipes mailing list (in order to improve my own understanding).

You might be interested in having a look: https://groups.google.com/forum/#!topic/haskell-pipes/Wtxumeo4JYE

Basically I believe `execU` could be removed and `delay` implements as such:

```
delay = P.mapM (<$ threadDelay (flags_update_interval * 1000))
```

Alternatively, `execU` could be rewritten:

```
execU mOp = (lift mOp >> await) >~ cat
```

which is equivalent to your original implementation.

Of course it doesn't matter much ... I am merely abusing the usage of "Issue" as I have found the discussion quite interesting.

**Comment by klao** [comment]
Hi Pierre,

Just a quick reply to your suggestions, but I will definitely take a look at the discussion later!

The `delay = P.mapM (<$ threadDelay s)` is a bit different from what I want. It waits "on the way down" in the pipe and not on the way up as the current one. (It basically results in the data being always obsolete by one period.) So, this is a nice way to write `execD`.

The second snippet is indeed a nice idiomatic way to define `execU`. I'll rewrite it as that, unless we find something even nicer. ;)

And no problem at all for this "issue"! I like this kind of discussion a lot, so thank you for it!
